[package]
name = "intcode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
konst = "0.2.18"
itertools = "0.8.2"
num-complex = "0.4"
